name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: Jiandong-Labs/github-workflow/.github/workflows/gradle.yml@main
    with:
      run-jacoco-badge: true
    secrets:
      GRADLE_CACHE_ENCRYPTION_KEY: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}